#!/usr/bin/env ruby
def move(view)
  case view
  when /-bb....../ then 0
  when /b-b....../ then 1
  when /bb-....../ then 2
  when /...-bb.../ then 3
  when /...b-b.../ then 4
  when /...bb-.../ then 5
  when /......-bb/ then 6
  when /......b-b/ then 7
  when /......bb-/ then 8
  when /-..b..b../ then 0
  when /b..-..b../ then 3
  when /b..b..-../ then 6
  when /.-..b..b./ then 1
  when /.b..-..b./ then 4
  when /.b..b..-./ then 7
  when /..-..b..b/ then 2
  when /..b..-..b/ then 5
  when /..b..b..-/ then 8
  when /-...b...b/ then 0
  when /b...-...b/ then 4
  when /b...b...-/ then 8
  when /..-.b.b../ then 2
  when /..b.-.b../ then 4
  when /..b.b.-../ then 6
  else nil
  end
end
board = ARGV[0]
swap = board.count('0') >= board.count('x') ? '0x' : 'x0'
puts move(board.tr(swap, 'ab')) ||
     move(board.tr(swap, 'ba')) ||
     [0, 8, 6, 2, 4, 1, 3, 5, 7].find { |i| board.slice(i, 1) == '-' }

