#!/usr/bin/env ruby
def move(view)
  case view
  when /-bb....../ then 0
  when /b-b....../ then 1
  when /bb-....../ then 2
  when /...-bb.../ then 3
  when /...b-b.../ then 4
  when /...bb-.../ then 5
  when /......-bb/ then 6
  when /......b-b/ then 7
  when /......bb-/ then 8
  when /-..b..b../ then 0
  when /b..-..b../ then 3
  when /b..b..-../ then 6
  when /.-..b..b./ then 1
  when /.b..-..b./ then 4
  when /.b..b..-./ then 7
  when /..-..b..b/ then 2
  when /..b..-..b/ then 5
  when /..b..b..-/ then 8
  when /-...b...b/ then 0
  when /b...-...b/ then 4
  when /b...b...-/ then 8
  when /..-.b.b../ then 2
  when /..b.-.b../ then 4
  when /..b.b.-../ then 6
  else nil
  end
end
board = ARGV[0]
player = board.count('0') >= board.count('x') ? '0' : 'x'
defend = move board.tr(player, 'a').tr('0x', 'b')
attack = move board.tr(player, 'b').tr('0x', 'a')
if defend
  puts defend
elsif attack
  puts attack
else
  puts [4, 0, 2, 6, 8, 1, 3, 5, 7].find { |i| board.slice(i, 1) == '-' }
end

